name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Install X11 and Wayland dev headers on Ubuntu
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libxcb-composite0-dev xorg-dev libwayland-dev pkg-config
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true
      - name: Cache cargo registry
        uses: actions/cache@v3
        with:
          path: ~/.cargo/registry
          key: ${{ runner.os }}-cargo-registry-${{ hashFiles('**/Cargo.lock') }}
      - name: Cache cargo index
        uses: actions/cache@v3
        with:
          path: ~/.cargo/git
          key: ${{ runner.os }}-cargo-git-${{ hashFiles('**/Cargo.lock') }}
      - name: cargo check
        run: cargo check --all-targets
      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets --all-features -- -D warnings
      - name: Build
        run: cargo build --all-targets --verbose
      - name: Tests
        run: cargo test --verbose
      - name: Smoke run
        run: cargo run -- --help
      - name: Chunking smoke test
        run: cargo run -- --stdout --no-clipboard -c 3000 README.md
      - name: cargo fmt
        run: cargo fmt --check
      - name: Clippy (deny warnings)
        run: cargo clippy --all-targets -- -D warnings
